name: pragma_acercamiento
description: "A new Flutter project with flavor support and UI Kit integration."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & DI
  get_it: ^8.0.2

  # Navigation
  go_router: ^14.6.2

  # Utilities
  path_provider: ^2.1.5
  bootstrap_icons: ^1.13.0

  # Local Packages
  ui_kit:
    path: packages/ui_kit
  router_core:
    path: packages/router_core
  network_manager:
    path: packages/network_manager
  local_storage_manager:
    path: packages/local_storage_manager
  objectbox: ^5.2.0
  objectbox_flutter_libs: ^5.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  objectbox_generator: ^5.2.0
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
