name: network_manager
description: A new Flutter package for managing network requests using Dio.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: ^3.35.7

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  talker: ^4.1.0
  talker_dio_logger: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
