name: widgetbook_app
description: Widgetbook showcase for Pragma UI Kit
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.10.0
  ui_kit:
    path: ../packages/ui_kit
  pragma_acercamiento:
    path: ../
  widgetbook_annotation: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.10.0
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
